export const yemek = {
    kahvalti: [
        { id: 1, name: "Sahanda yumurta", price: "29 000", description: "Saryoğ tuhum zirovor", imgSrc: "./kahvalti/kahvalti1.jpg" },
        { id: 2, name: "Kavurmalı yumurta", price: "59 000", description: "Qovurdoğ saryoğ tuhum zirovor", imgSrc: "./kahvalti/kahvalti2.jpg" },
        { id: 3, name: "Menemen", price: "49 000", description: "Balgariskiy pamidor tamatzirovorlar tuhum sir saryogi", imgSrc: "./kahvalti/kahvalti0.jpg" },
        { id: 4, name: "Sucuklu yumurta", price: "39 000", description: "Türk kalbasa tuhum saryoğ zirovor", imgSrc: "./kahvalti/kahvalti3.jpg" },
        { id: 5, name: "Serpme Kahvaltı", price: "299 000", description: "2 Kişilik", imgSrc: "./kahvalti/kahvalti4.jpg" },
        { id: 6, name: "Kahvaltı tabağı", price: "59 000", description: "1  Kişilik", imgSrc: "./kahvalti/kahvalti5.jpg" },
    ],
    corbalar: [
        { id: 7, name: "Ezo gelin çorba", price: "32 000", description: "Qalampirli", imgSrc: "./chorbalar/chorba2.jpg" },
        { id: 8, name: "Marcimek", price: "32 000", description: "", imgSrc: "./chorbalar/chorba1.jpg" },
        { id: 9, name: "Tavuk çorbası", price: "32 000", description: "", imgSrc: "./chorbalar/chorba3.jpg" },
        { id: 10, name: "Kelle paça antep", price: "69 000", description: "", imgSrc: "./chorbalar/chorba4.jpg" },
    ],
    siciklar: [
        { id: 11, name: "Prinç pilavı", price: "29 000", description: "", imgSrc: "./chorbalar/pilav.jpg" },
        { id: 12, name: "Bulgur pilavı", price: "29 000", description: "", imgSrc: "./chorbalar/pilav1.jpg" },
        { id: 13, name: "Çiğ Köfte", price: "59 000", description: "Italian Style Pasta", imgSrc: "./chorbalar/fri3.JPG" },
        { id: 14, name: "Fri normal", price: "35 000", description: "Classic Turkish Burger", imgSrc: "./chorbalar/fri2.JPG" },
        { id: 15, name: "Patates fri elma", price: "39 000", description: "Mal etindan yapilan steak", imgSrc: "./chorbalar/fri1.JPG" },
    ],
    salatalar: [ 
        { id: 16, name: "Çoban Salata", price: "49 000", description: "", imgSrc: "./salatalar/salat1.jpg" },
        { id: 17, name: "Buratto salat", price: "89 000", description: "", imgSrc: "./salatalar/salat2.jpg" },
        { id: 18, name: "Çitir patlican salata", price: "89 000", description: "", imgSrc: "./salatalar/salat3.JPG" },
        { id: 19, name: "Gavurdaği salata", price: "69 000", description: "", imgSrc: "./salatalar/salat4.jpg" },
        { id: 20, name: "Sezer salata", price: "69 000", description: "", imgSrc: "./salatalar/salat5.jpg" },
        { id: 21, name: "Çitir tavuklu salata", price: "89 000", description: "", imgSrc: "./salatalar/salat6.jpg" },
        { id: 22, name: "Yapon salat", price: "79 000", description: "", imgSrc: "./salatalar/salat7.JPG" },
        { id: 23, name: "Gretiskiy salat", price: "69 000", description: "", imgSrc: "./salatalar/salat8.jpg" },
        { id: 24, name: "Mevsim salata", price: "55 000", description: "", imgSrc: "./salatalar/salat9.jpg" },
        { id: 25, name: "Steak salata rukulalik", price: "119 000", description: "", imgSrc: "./salatalar/salat10.JPG" },
        { id: 26, name: "Rukula salata klassik", price: "69 000", description: "", imgSrc: "./salatalar/salat11.jpg" },
        { id: 27, name: "Tavuklu rukula salata", price: "79 000", description: "", imgSrc: "./salatalar/salat12.jpg" },
        { id: 28, name: "Qoziqorinlik rukula salata", price: "89 000", description: "", imgSrc: "./salatalar/salat14.jpg" },
        { id: 29, name: "Tulum salata", price: "89 000", description: "", imgSrc: "./salatalar/salat15.jpg" },
        { id: 30, name: "Fruktovi salat", price: "89 000", description: "", imgSrc: "./salatalar/salat16.jpg" },
        { id: 31, name: "Avakado salat", price: "69 000", description: "", imgSrc: "./salatalar/salat17.jpg" },
        { id: 32, name: "Ezme", price: "35 000", description: "", imgSrc: "./salatalar/salat18.jpg" },
        { id: 33, name: "Haydari", price: "29 000", description: "", imgSrc: "./salatalar/salat19.jpg" },
        { id: 34, name: "Pişmiş Soğan", price: "29 000", description: "", imgSrc: "./salatalar/salat20.jpg" },
        { id: 35, name: "Fransuz salata", price: "69 000", description: "", imgSrc: "./salatalar/salat21.jpg" },
        { id: 36, name: "Olivie salat", price: "49 000", description: "", imgSrc: "./salatalar/salat22.jpg" },
        { id: 37, name: "Yaprak sarma", price: "29 000", description: "", imgSrc: "./salatalar/salat23.jpg" },
    ],
    pide: [
        { id: 38, name: "Kiymali pide", price: "79 000", description: "", imgSrc: "./pide/pide1.jpg" },
        { id: 39, name: "Karişik pide", price: "99 000", description: "", imgSrc: "./pide/pide2.jpg" },
        { id: 40, name: "Kuşbaşili pide", price: "79 000", description: "", imgSrc: "./pide/pide3.jpg" },
        { id: 41, name: "kaşarli balli pide (asalli)", price: "69 000", description: "", imgSrc: "./pide/pide4.jpg" },
        { id: 42, name: "Kuşbaşi kaşarli pide", price: "89 000", description: "", imgSrc: "./pide/pide5.jpg" },
        { id: 43, name: "Kaymakli balli fistikli pide", price: "99 000", description: "", imgSrc: "./pide/pide7.jpg" },
        { id: 44, name: "Antep Lahmacun", price: "35 000", description: "", imgSrc: "./pide/pide6.jpg" },
    ],
    burger: [
        { id: 45, name: "Süper Bomba Döner", price: "149 000", description: "", imgSrc: "./pide/burger1.jpg" },
        { id: 46, name: "Kuddus burger", price: "99 000", description: "", imgSrc: "./pide/burger2.JPEG" },
        { id: 47, name: "Döner Burger", price: "89 000", description: "", imgSrc: "./pide/burger3.JPEG" },
    ],
    spaghetti:[
        { id: 48, name: "kiymali spagetti", price: "99 000", description: "", imgSrc: "spagetti.jpg" },
        { id: 49, name: "Ton balıklı spagetti", price: "99 000", description: "", imgSrc: "spagetti.jpg" },
        { id: 50, name: "Penna arabiatta", price: "99 000", description: "", imgSrc: "spagetti.jpg" },
        { id: 51, name: "fenna arabia", price: "99 000", description: "", imgSrc: "spagetti.jpg" },
        { id: 52, name: "feto chino", price: "99 000", description: "", imgSrc: "spagetti.jpg" },
        { id: 53, name: "steack spagetti", price: "149 000", description: "", imgSrc: "spagetti.jpg" },
    ],  
    pizza: [
        { id: 54, name: "Istanbul pizza karişik", price: "119 000", description: "", imgSrc: "pizza.png" },
        { id: 55, name: "Nutellalı pizza", price: "149 000", description: "", imgSrc: "pizza.png" },
        { id: 56, name: "Pepperon pizza", price: "119 000", description: "", imgSrc: "pizza.png" },
        { id: 57, name: "Go'shtli pizza", price: "189 000", description: "", imgSrc: "pizza.png" },
        
    ],
    doner: [
        { id: 58, name: "Mehur iskender kebap", price: "110 000", description: "", imgSrc: "./chorbalar/doner.JPG" },
        { id: 59, name: "Pilav ustu Döner", price: "105 000", description: " Döner/140gr, Pilav/60gr", imgSrc: "./chorbalar/doner0.JPEG" },
        { id: 60, name: "Yaprak Döner(140gr)", price: "99 000", description: " ", imgSrc: "./chorbalar/doner2.JPEG" },

    ],
    kebaplar: [
        { id: 61, name: "Meşhur beyti kebap", price: "110 000", description: "", imgSrc: "./kebaplar/kebap1.JPG" },
        { id: 62, name: "köri soslu bonfile", price: "160 000", description: "", imgSrc: "./kebaplar/kebap2.JPG" },
        { id: 63, name: "köri soslu tavuk", price: "129 000", description: "", imgSrc: "./kebaplar/kebap2.JPG" },
        { id: 64, name: "Adana kebap acili ", price: "99 000", description: "Urfa Kebap", imgSrc: "./kebaplar/kebap3.JPG" },
        { id: 65, name: "Et şiş ", price: "119 000", description: "", imgSrc: "./kebaplar/kebap4.JPG" },
        { id: 66, name: "Çop şiş (Viriska)", price: "119 000", description: "", imgSrc: "./kebaplar/kebap5.JPG" },
        { id: 67, name: "Tavuk şiş ", price: "89 000", description: "", imgSrc: "./kebaplar/kebap6.JPG" },
        { id: 68, name: "Domates kebap ", price: "69 000", description: "", imgSrc: "./kebaplar/kebap7.JPG" },
        { id: 69, name: "Patlican kebap ", price: "49 000", description: "", imgSrc: "./kebaplar/kebap8.JPG" },
        { id: 70, name: "Karişik Kebap (2 kişilik) ", price: "299 000", description: "   4 kişilik 599 000 so'm  / 6  kişilik 899 000", imgSrc: "./kebaplar/kebap9.JPG" },
        { id: 71, name: "Metrelik Kebap ", price: "349 000", description: "1-metr", imgSrc: "./kebaplar/5.JPEG" },
    ],
    tava: [
        { id: 72, name: "Saç kavurma etli", price: "149 000", description: "", imgSrc: "./kebaplar/tava1.JPG" },
        { id: 73, name: "Saç kavurma Tavuklu", price: "129 000", description: "", imgSrc: "./kebaplar/tava1.JPG" },
        { id: 74, name: "Ali nazik şiş", price: "139 000", description: "", imgSrc: "./kebaplar/tava2.JPG" },
        { id: 75, name: "Ali nazik kebap", price: "129 000", description: "", imgSrc: "./kebaplar/tava3.JPG" },

    ],
    shef: [
        { id: 76, name: "Kuddus Kiremit", price: "199 000", description: "(2 kişilik) 500gr Taliq gosht balgarski pamidor saryog 4 soat tandirda pishkan", imgSrc: "she1.png" },
        { id: 77, name: "Kuşbaşili kaşarli kiremit ", price: "149 000", description: "(2 kişilik) Viriska pamidor balgarskiy sir saryog sous 4 soat tandirda pishkan", imgSrc: "./kebaplar/4.JPG " },
    ],
    steak: [
        { id: 78, name: "Kaşarli XL köfte", price: "299 000", description: "", imgSrc: "./kebaplar/stek1.JPG" },
        { id: 79, name: "Biftek", price: "199 000", description: "", imgSrc: "./kebaplar/ste3.JPEG" },
        { id: 80, name: "Kuzu Pirzola", price: "199 000", description: "", imgSrc: "./kebaplar/stek2.JPEG" },
        { id: 81, name: "Steak Assorti (2 kişilik)", price: "499 000", description: "(3 kişilik / 749,000 so'm) (4 kişilik / 999,000 so'm) ", imgSrc: "./kebaplar/stek6.JPG" }, 
        { id: 82, name: "Steak Assorti (5 kişilik)", price: "1,249,000", description: " (6 kişilik/1,499,000so'm) ", imgSrc: "./kebaplar/stek6.JPG" }, 
        { id: 83, name: "Kuzu kol steak", price: "799 000", description: "4 kişilik", imgSrc: "./kebaplar/stek7.jpg" },
        { id: 84, name: "Asado kaburga steak ", price: "399 000", description: "(2 kişilik) 4 kişilik 649 000", imgSrc: "./kebaplar/stek5.jpg" },
        { id: 85, name: "Kuzu Tandir (250gr)", price: "149 000", description: "(1kg 599 000)", imgSrc: "./kebaplar/stek4.png" },
        { id: 86, name: "Ananasli Bonfile", price: "299 000", description: "", imgSrc: "./stek/stak1.jpg" },
        { id: 87, name: "Dallas Steak", price: "349 000", description: "500gr / 600gr", imgSrc: "./stek/stak2.jpg" },
        { id: 88, name: "T bon Steak", price: "349 000", description: "450gr / 500gr", imgSrc: "./stek/stak3.jpg" },
        { id: 89, name: "Ribay Steak", price: "299 000", description: "450gr / 500gr", imgSrc: "./stek/stak4.jpg" },
        { id: 90, name: "Terayağli Bonfile Steak", price: "399 000", description: "500gr / 600gr", imgSrc: "./stek/stak5.jpg" },
        { id: 91, name: "Terayağli Bonfile Steak", price: "799 000", description: "3-4 kişilik", imgSrc: "./stek/stak5.jpg" },
    ],      
    tatli: [
        { id: 92, name: "Havuç Dilim Baklava", price: "89 000", description: "", imgSrc: "./tatlilar/tatli1.jpg" },
        { id: 93, name: "Midye Baklava", price: "39 000", description: "", imgSrc: "./tatlilar/tatli2.jpg" },
        { id: 94, name: "Kare Baklava", price: "39 000", description: "", imgSrc: "./tatlilar/tatli3.jpg" },
        { id: 95, name: "Antep Baklava", price: "99 000", description: "", imgSrc: "./tatlilar/tatli4.jpg" },
        { id: 96, name: "Sarma Baklava", price: "49 000", description: "", imgSrc: "./tatlilar/tatli5.jpg" },
        { id: 97, name: "Sutlaç", price: "49 000", description: "Sut guruch shakar", imgSrc: "./tatlilar/tatli8.jpg" },
        { id: 98, name: "Antep Künefe", price: "89 000", description: "", imgSrc: "./tatlilar/tatli7.JPG" },
        { id: 99, name: "Fruktoviy Assorti", price: "249 000", description: "", imgSrc: "./tatlilar/fruk.JPG" },
    ],
    ekmek:[ 
        { id: 100, name: "Non Assarti", price: "39 000", description: "", imgSrc: "./tatlilar/non.JPG" },
        { id: 101, name: "Balon Ekmek", price: "19 000", description: "", imgSrc: "./tatlilar/non1.JPG" },
        { id: 102, name: "Avğon Ekmek", price: "29 000", description: "", imgSrc: "./tatlilar/non2.JPG" },
        { id: 103, name: "Ekmek Pide Donasi", price: "6 000", description: "", imgSrc: "./tatlilar/non3.JPG" },
    ],
    suv: [
        { id: 104, name: "Türk kahvesi", price: "29 000", description: "", imgSrc: "./suvlar/kahva1.jpg" },
        { id: 105, name: "Türk çayi bardak", price: "6 000", description: "", imgSrc: "./suvlar/choy.jpg" },
        { id: 106, name: "Türk Demlik çay", price: "39 000", description: "", imgSrc: "./suvlar/choynak.jpg" },
        { id: 107, name: "Yeşil çay", price: "15 000", description: "", imgSrc: "./suvlar/choy.jpg" },
        { id: 108, name: "Meşhur Türk Ayrani", price: "19 000", description: "", imgSrc: "./suvlar/ayron.jpg" },
        { id: 109, name: "Cola kutu(0.5)", price: "25 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 110, name: "Cola kutu (0.33)", price: "22 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 111, name: "Cola şişe", price: "24 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 112, name: "Cola zero kutu ", price: "22 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 113, name: "Cola zero şişe", price: "24 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 114, name: "Fanta şişe", price: "24 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 115, name: "Sprite şişe", price: "24 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 116, name: "Chortok", price: "19 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 117, name: "Meva sharbat/1l", price: "49 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 118, name: "Ays tea", price: "89 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 119, name: "Tarhun", price: "89 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 120, name: "Maxito", price: "89 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 121, name: "Bardak ise tea", price: "29 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 122, name: "şalgam suyu", price: "25 000", description: "", imgSrc: "./suvlar/suv.jpg" },
        { id: 123, name: "Türk soda", price: "19 000", description: "", imgSrc: "./suvlar/suv.jpg" },
    ],
};

console.log(yemek);
